name: Destroy Infrastructure

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      confirm:
        description: 'Type "destroy" to confirm'
        required: true
        default: ''

env:
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

jobs:
  destroy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Validate Confirmation
      run: |
        if [ "${{ github.event.inputs.confirm }}" != "destroy" ]; then
          echo "❌ Confirmation failed. You must type 'destroy' to proceed."
          exit 1
        fi
        echo "✅ Confirmation received. Proceeding with destroy..."

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      working-directory: terraform
      env:
        TF_VAR_aws_region: ${{ env.AWS_REGION }}
      run: terraform init -backend-config="region=$TF_VAR_aws_region"

    - name: Terraform Destroy
      working-directory: terraform
      env:
        TF_VAR_aws_region: ${{ env.AWS_REGION }}
        TF_VAR_key_name: ${{ secrets.EC2_KEY_NAME || '' }}
      run: |
        terraform destroy -auto-approve \
          -var="aws_region=$TF_VAR_aws_region" \
          -var="key_name=$TF_VAR_key_name"

    - name: Summary
      if: always()
      run: |
        echo "## Destroy Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ $? -eq 0 ]; then
          echo "✅ **Infrastructure Destroyed Successfully**" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Destroy Failed - Check logs above**" >> $GITHUB_STEP_SUMMARY
        fi
